#pragma once

#ifndef ECC_FRONTEND_H
#define ECC_FRONTEND_H

#include "error.hpp"
#include "util.hpp"

namespace ecc::driver {
struct TranslationUnit;
}

namespace ecc::frontend {
/* Frontend driver code.

Most frontend driver functionality is generated by Flex/Bison from
our parser.y and scanner.l files. This driver code just calls yyparse(),
returning the completed ASTNode when done.

*/

class ParseError : public EccError {
public:
    ParseError(std::string err, Location loc) : EccError(ErrorSource::PARSE, err, loc) {}
};

// The object driving the Frontend's functionality.
class Frontend {
public:
    // Frontend();

    ~Frontend() = default;

    // Run the frontend on file `f`. Returns 0 on success.
    void run(driver::TranslationUnit& unit);
};

} // namespace ecc::frontend

#endif