#ifndef ECC_PARSER_HPP

namespace ecc::frontend {

/* Frontend driver code.

Most frontend driver functionality is generated by Flex/Bison from
our parser.y and scanner.l files. This driver code just calls yyparse(),
returning the completed ASTNode when done.

*/

// The object driving the Frontend's functionality.
class Frontend {

};

}

#endif