#ifndef ECC_FRONTEND_H
#define ECC_FRONTEND_H

#include <string>

#include "frontend/tokens.hpp"
#include "parser.hpp"

namespace ecc::frontend {

/* Frontend driver code.

Most frontend driver functionality is generated by Flex/Bison from
our parser.y and scanner.l files. This driver code just calls yyparse(),
returning the completed ASTNode when done.

*/

// The object driving the Frontend's functionality.
class Frontend {
public:
    // Frontend();

    ~Frontend() = default;

    int result;

    // Run the frontend on file `f`. Returns 0 on success.
    int parse(const std::string& filename);
};

// Convert a Bison-defined token to a Tokentype.
ecc::tokens::TokenType p_tok_to_toktype(ecc::parser::Parser::token* tok);

} // namespace ecc::frontend

#endif