#ifndef ECC_FRONTEND_H
#define ECC_FRONTEND_H

#include <string>
#include <map>

namespace ecc::frontend {

/* Frontend driver code.

Most frontend driver functionality is generated by Flex/Bison from
our parser.y and scanner.l files. This driver code just calls yyparse(),
returning the completed ASTNode when done.

*/

// The object driving the Frontend's functionality.
class Frontend {
public:
    Frontend();

    ~Frontend() = default;

    std::map<std::string, int> variables;

    int result;
    
    // Run the frontend on file `f`. Returns 0 on success.
    int parse(const std::string& f);

    std::string file;

    void lex_begin();

    void lex_end();

    bool trace_parsing;
    bool trace_lexing;
};

}

#endif