%skeleton "lalr1.cc"
%require "3.2"
%language "c++"
%locations

%defines
// Define the namespace and class name generated by Bison
%define api.namespace {ecc::parser}
%define api.parser.class {Parser}

%{

#include <iostream>

#include "frontend/frontend.hpp"
#include "ast/ast.hpp"
    
%}

%% // RULES

program:
    %empty {  /* actions go here */   }

%% // EPILOGUE
