%skeleton "lalr1.cc"
%require "3.2"
%language "c++"
%locations

%defines
// Define the namespace and class name generated by Bison
%define api.namespace {ecc::frontend}
%define api.parser.class {Parser}
%define api.value.type variant
%define api.token.constructor
%define api.location.type {ecc::location::Location}
// temp to debug
%define parse.trace
// todo: create custom error messages
%define parse.error verbose


// Use `code requires` to ensure it gets injected into the header file as well.
%code requires {

#include <set>
#include <memory>
#include "ast/ast.hpp"
#include "util.hpp"
#include "allocator/alloc.hpp"
#include "allocator/chunk.hpp"

using namespace ecc::ast;
using namespace ecc::util;

// Quick forward declaration to satisfy function signatures, this is just for .hpp.
// The full Lexer declaration is included in the .cpp (see %code below).
namespace ecc::frontend {
class Lexer;
}

}

// Add new parameters to the parser function, which will be passed to the lexer and used to build the AST.
%parse-param { ecc::frontend::Lexer &lexer }
%parse-param { ecc::ast::Program &ast_root }
// lexer hack bodge
%parse-param { std::set<std::string>& type_idents }

%lex-param { ecc::frontend::Lexer &lexer }

// `code` sans requires to include in the .cpp file only,
%code {

#include "frontend/lexer.hpp"
#include "frontend/frontend.hpp"

static ecc::frontend::Parser::symbol_type yylex(ecc::frontend::Lexer& lexer) {
    return lexer.get_next_token();
}

}

// Tokens
%token 
    <std::string> 
    IDENTIFIER "identifier"
    STRING_LITERAL "string literal"
    TYPE_IDENTIFIER "type"
    <uint64_t> 
    INT_CONST "integer literal"
    <double> 
    FLOAT_CONST "float literal"
    <char> 
    CHAR_CONST "character literal"

// Keywords
%token 
    IF       "if"
    ELSE     "else"
    WHILE    "while"
    DO       "do"
    FOR      "for"
    SWITCH   "switch"
    CASE     "case"
    DEFAULT  "default"
    BREAK    "break"
    CONTINUE "continue"
    RETURN   "return"
    GOTO     "goto"
    CLASS    "class"
    UNION    "union"
    ENUM     "enum"
    CONST    "const"
    VOID     "void"
    U8       "U8"
    U16      "U16"
    U32      "U32"
    U64      "U64"
    I8       "I8"
    I16      "I16" 
    I32      "I32"
    I64      "I64"
    F32      "F32"
    F64      "F64"
    BOOL     "Bool"
    SIZEOF   "sizeof"
    PUBLIC   "public"
    STATIC   "static"
    EXTERN   "extern"
    TRUE     "true"
    FALSE    "false"

// Operators
%token
    PLUS     "+"
    MINUS    "-"
    MUL      "*"
    DIV      "/"
    MOD      "%"
    ASSIGN   "="
    EQ       "=="
    NE       "!="
    LE       "<="
    GE       ">="
    ANDAND   "&&"
    OROR     "||"
    INC      "++"
    DEC      "--"
    PLUSEQ   "+="
    MINUSEQ  "-="
    MULEQ    "*="
    DIVEQ    "/="
    MODEQ    "%="
    LSHIFTEQ "<<="
    RSHIFTEQ ">>="
    ANDEQ    "&="
    OREQ     "|="
    XOREQ    "^="
    AND      "&"
    OR       "|"
    XOR      "^"
    TILDE    "~"
    NOT      "!"
    LT       "<"
    GT       ">"
    LSHIFT   "<<" 
    RSHIFT   ">>"
    SEMI     ";"
    COMMA    ","
    LPAREN   "("
    RPAREN   ")"
    LBRACE   "{"
    RBRACE   "}"
    LBRACKET "["
    RBRACKET "]"
    AT       "@"
    DOT      "."
    ARROW    "->"
    COLON    ":"
    QUESTION "?"
    ELLIPSIS "..."

// Operator precedence.
%left OROR
%left ANDAND
%left OR
%left XOR
%left AND
%left EQ NE
%left LT GT LE GE
%left LSHIFT RSHIFT
%left PLUS MINUS
%left MUL DIV MOD

//for ternary
%nonassoc QUESTION

%glr-parser
%expect 8

// Nonterminal type specifications.
//* Note: the default Bison action will NOT work on these, as std_unique ptr has move semantics.
//* All actions must be filled with { $$ = std::move($1); }.
%type <Chunk<Program>> program
%type <Chunk<ProgramItem>> program_item
%type <Chunk<Attribute>> attribute
%type <Chunk<AttributeArg>> attribute_arg
%type <Vec<Chunk<AttributeArg>>> attribute_arg_list
%type <Vec<Chunk<Attribute>>> attribute_list
%type <Chunk<Function>> function
%type <Chunk<Declaration>> declaration
%type <Chunk<Statement>> statement
%type <Chunk<Declarator>> declarator abstract_declarator
%type <Chunk<DirectDeclarator>> direct_abstract_declarator
%type <Vec<Chunk<ProgramItem>>> stmt_or_decl_list

%type <Vec<Chunk<DeclarationSpecifier>>> declaration_specifier_list specifier_qualifier_list
%type <Chunk<DeclarationSpecifier>> storage_class_specifier type_specifier
%type <Chunk<PrimitiveSpecifier>> primitive_type
%type <Chunk<ClassSpecifier>> class_specifier
%type <Chunk<UnionSpecifier>> union_specifier
%type <Chunk<TypeQualifier>> type_qualifier
%type <Vec<Chunk<TypeQualifier>>> type_qualifier_list
%type <Chunk<TypeIdentifier>> type_identifier

%type <Chunk<InitDeclarator>> init_declarator
%type <Vec<Chunk<InitDeclarator>>> init_declarator_list
%type <ecc::tokens::AssignOp> assignment_operator
%type <ecc::tokens::UnaryOp> unary_operator

%type <Chunk<Pointer>> pointer
%type <Chunk<DirectDeclarator>> direct_declarator
%type <Vec<Chunk<ParameterDeclaration>>> parameter_list
%type <Chunk<ParameterDeclaration>> parameter_declaration
%type <std::pair<Vec<Chunk<ParameterDeclaration>>, bool>> parameter_type_list

%type <Chunk<EnumSpecifier>> enum_specifier
%type <Vec<Chunk<ClassDeclaration>>> member_declaration_list
%type <Chunk<ClassDeclaration>> class_declaration
%type <Vec<Chunk<ClassDeclarator>>> class_declarator_list
%type <Chunk<ClassDeclarator>> member_declarator
%type <Vec<Chunk<Enumerator>>> enumerator_list
%type <Chunk<Enumerator>> enumerator
%type <Vec<std::string>> class_parent_list
%type <std::string> class_parent

%type <Chunk<TypeName>> type_name
%type <Chunk<Initializer>> initializer designated_initializer
%type <Vec<Chunk<Initializer>>> initializer_list

%type <Chunk<CompoundStatement>> compound_statement
%type <Chunk<Statement>> labeled_statement expression_statement print_statement
%type <Chunk<Statement>> selection_statement iteration_statement jump_statement

%type <Chunk<Expression>> expression assignment_expression conditional_expression
%type <Chunk<Expression>> unary_expression postfix_expression
%type <Chunk<Expression>> primary_expression cast_expression logical_and_expression
%type <Chunk<Expression>> logical_or_expression inclusive_or_expression
%type <Chunk<Expression>> exclusive_or_expression and_expression equality_expression
%type <Chunk<Expression>> relational_expression shift_expression additive_expression
%type <Chunk<Expression>> multiplicative_expression
%type <Chunk<LiteralExpression>> constant
%type <std::string> string_literal
%type <Chunk<ConstExpression>> constant_expression
%type <Vec<Chunk<Expression>>> argument_expression_list
%type <Optional<ForStatement::ForInit>> for_init_opt
%type <Optional<Chunk<Expression>>> expression_opt

%%

/* Program */
program:
    %empty { }
    | program program_item {
        ast_root.add_item(std::move($2));
    }
;

attribute:
    AT LBRACKET attribute_arg_list RBRACKET {
        $$ = make_chunk<Attribute>(@$, std::move($3));
    }
;

attribute_arg:
    IDENTIFIER {
        $$ = make_chunk<AttributeArg>(@1, std::move($1), std::nullopt);
    }
    | IDENTIFIER ASSIGN STRING_LITERAL {
        $$ = make_chunk<AttributeArg>(@$, std::move($1), std::move($3));
    }
;

attribute_arg_list:
    attribute_arg {
        Vec<Chunk<AttributeArg>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | attribute_arg_list COMMA attribute_arg {
        $1.push_back(std::move($3));
        $$ = std::move($1);
    }
;

// One or more stacked `#[...]` attributes, e.g. `#[foo] #[bar = "baz"]`.
attribute_list:
    attribute {
        Vec<Chunk<Attribute>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | attribute_list attribute {
        $1.push_back(std::move($2));
        $$ = std::move($1);
    }
;

// Program item
program_item:
    function { $$ = std::move($1); }
    | statement { $$ = std::move($1); }
    | declaration { $$ = std::move($1); }
    // Attributes only attach to functions and declarations, not bare statements.
    | attribute_list function {
        $2->attributes = std::move($1);
        $$ = std::move($2);
    }
    | attribute_list declaration {
        $2->attributes = std::move($1);
        $$ = std::move($2);
    }
    | attribute_list statement {
        error(@$, "attributes cannot be applied to statements");
        return 1;
    }
;

// Function definitions
function:
    declaration_specifier_list declarator compound_statement {
        $$ = make_chunk<Function>(@$, std::move($1), std::move($2), std::move($3));
    }
;

declaration_specifier_list:
    type_specifier { // ensure that the type specifier is the last node in the list
        Vec<Chunk<DeclarationSpecifier>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | storage_class_specifier declaration_specifier_list {
        $2.push_back(std::move($1));
        $$ = std::move($2);
    }
    | type_qualifier declaration_specifier_list {
        $2.push_back(std::move($1));
        $$ = std::move($2);
    }
;

storage_class_specifier:
    PUBLIC { $$ = make_chunk<StorageClassSpecifier>(@1, StorageClassSpecifier::PUBLIC); }
    | STATIC { $$ = make_chunk<StorageClassSpecifier>(@1, StorageClassSpecifier::STATIC); }
    | EXTERN { $$ = make_chunk<StorageClassSpecifier>(@1, StorageClassSpecifier::EXTERN); }
    | EXTERN STRING_LITERAL {
        if ($2 != "C") { // fixme: this is a bodge
            error(@$, "only \"C\" linkage is supported");
            return 1;
        }
        $$ = make_chunk<StorageClassSpecifier>(@1, StorageClassSpecifier::EXTERNC);
    }
;

type_specifier:
    VOID { $$ = make_chunk<VoidSpecifier>(@1); }
    | type_identifier { $$ = std::move($1); }
    | primitive_type { $$ = std::move($1); }
    | class_specifier { $$ = std::move($1); }
    | union_specifier { $$ = std::move($1); }
    | enum_specifier { $$ = std::move($1); }
;

class_specifier:
    // Class specifier with definition and parent classes.
    CLASS IDENTIFIER COLON class_parent_list LBRACE member_declaration_list RBRACE {
        type_idents.insert($2);
        $$ = make_chunk<ClassSpecifier>(@$, std::move($2), std::move($4), std::move($6));
    }
    | CLASS TYPE_IDENTIFIER COLON class_parent_list LBRACE member_declaration_list RBRACE {
        $$ = make_chunk<ClassSpecifier>(@$, std::move($2), std::move($4), std::move($6));
    }
    // Adding parent classes is part of the class definition, so if no members follow a
    // class declaration with a parent list, that is a syntactic error.
    | CLASS IDENTIFIER COLON class_parent_list {
        error(@$, "incomplete class definition");
        return 1;
    }
    | CLASS TYPE_IDENTIFIER COLON class_parent_list {
        error(@$, "incomplete class definition");
        return 1;
    }
    // Class specifier with definition.
    | CLASS IDENTIFIER LBRACE member_declaration_list RBRACE {
        type_idents.insert($2);
        $$ = make_chunk<ClassSpecifier>(@$, std::move($2), std::nullopt, std::move($4));
    }
    | CLASS TYPE_IDENTIFIER LBRACE member_declaration_list RBRACE {
        $$ = make_chunk<ClassSpecifier>(@$, std::move($2), std::nullopt, std::move($4));
    }
    // Anonymous class specifier with member declarations.
    | CLASS LBRACE member_declaration_list RBRACE {
        $$ = make_chunk<ClassSpecifier>(@$, std::nullopt, std::nullopt, std::move($3));
    }
    // Class specifier with no definition.
    | CLASS IDENTIFIER {
        type_idents.insert($2);
        $$ = make_chunk<ClassSpecifier>(@$, std::move($2), std::nullopt, std::nullopt);
    }
    | CLASS TYPE_IDENTIFIER {
        $$ = make_chunk<ClassSpecifier>(@$, std::move($2), std::nullopt, std::nullopt);
    }
;

union_specifier:
    // Union specifier with a type representative and definition.
    primitive_type UNION IDENTIFIER LBRACE member_declaration_list RBRACE {
        type_idents.insert($3);
        $$ = make_chunk<UnionSpecifier>(@$, std::move($3), $1->pkind, std::move($5));
    }
    | primitive_type UNION TYPE_IDENTIFIER LBRACE member_declaration_list RBRACE {
        $$ = make_chunk<UnionSpecifier>(@$, std::move($3), $1->pkind, std::move($5));
    }
    // Regular union specifier with definition.
    | UNION IDENTIFIER LBRACE member_declaration_list RBRACE {
        type_idents.insert($2);
        $$ = make_chunk<UnionSpecifier>(@$, std::move($2), std::nullopt, std::move($4));
    }
    | UNION TYPE_IDENTIFIER LBRACE member_declaration_list RBRACE {
        $$ = make_chunk<UnionSpecifier>(@$, std::move($2), std::nullopt, std::move($4));
    }
    // Anonymous union specifier with a type representative and definition.
    | primitive_type UNION LBRACE member_declaration_list RBRACE {
        $$ = make_chunk<UnionSpecifier>(@$, std::nullopt, $1->pkind, std::move($4));
    }
    // Regular anonymous union specifier with definition.
    | UNION LBRACE member_declaration_list RBRACE {
        $$ = make_chunk<UnionSpecifier>(@$, std::nullopt, std::nullopt, std::move($3));
    }
    // Adding a type representative is part of the union definition, so if no members
    // follow a union declaration with a primitive type, that is a syntactic error.
    | primitive_type UNION IDENTIFIER {
        error(@$, "incomplete union definition");
        return 1;
    }
    | primitive_type UNION TYPE_IDENTIFIER {
        error(@$, "incomplete union definition");
        return 1;
    }
    // Union specifier with no definition.
    | UNION IDENTIFIER {
        type_idents.insert($2);
        $$ = make_chunk<UnionSpecifier>(@$, std::move($2), std::nullopt, std::nullopt);
    }
    | UNION TYPE_IDENTIFIER {
        $$ = make_chunk<UnionSpecifier>(@$, std::move($2), std::nullopt, std::nullopt);
    }
;

primitive_type:
    U8 { $$ = make_chunk<PrimitiveSpecifier>(@1, ecc::tokens::PrimType::U8); }
    | U16 { $$ = make_chunk<PrimitiveSpecifier>(@1, ecc::tokens::PrimType::U16); }
    | U32 { $$ = make_chunk<PrimitiveSpecifier>(@1, ecc::tokens::PrimType::U32); }
    | U64 { $$ = make_chunk<PrimitiveSpecifier>(@1, ecc::tokens::PrimType::U64); }
    | I8 { $$ = make_chunk<PrimitiveSpecifier>(@1, ecc::tokens::PrimType::I8); }
    | I16 { $$ = make_chunk<PrimitiveSpecifier>(@1, ecc::tokens::PrimType::I16); }
    | I32 { $$ = make_chunk<PrimitiveSpecifier>(@1, ecc::tokens::PrimType::I32); }
    | I64 { $$ = make_chunk<PrimitiveSpecifier>(@1, ecc::tokens::PrimType::I64); }
    | F32 { $$ = make_chunk<PrimitiveSpecifier>(@1, ecc::tokens::PrimType::F32); }
    | F64 { $$ = make_chunk<PrimitiveSpecifier>(@1, ecc::tokens::PrimType::F64); }
    | BOOL { $$ = make_chunk<PrimitiveSpecifier>(@1, ecc::tokens::PrimType::BOOL); }
;

type_qualifier:
    CONST { $$ = make_chunk<TypeQualifier>(@1, TypeQualifier::CONST); }
;

class_parent_list:
    class_parent {
        Vec<std::string> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | class_parent_list COMMA class_parent {
        $1.push_back(std::move($3));
        $$ = std::move($1);
    }

class_parent:
    IDENTIFIER {
        $$ = std::move($1);
    }
    | TYPE_IDENTIFIER {
        $$ = std::move($1);
    }
    | CLASS IDENTIFIER {
        $$ = std::move($2);
    }
    | CLASS TYPE_IDENTIFIER {
        $$ = std::move($2);
    }

member_declaration_list:
    class_declaration {
        Vec<Chunk<ClassDeclaration>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | member_declaration_list class_declaration {
        $1.push_back(std::move($2));
        $$ = std::move($1);
    }
;

class_declaration:
    specifier_qualifier_list class_declarator_list SEMI {
        $$ = make_chunk<ClassDeclaration>(@$, std::move($1), std::move($2));
    }
;

specifier_qualifier_list:
    type_specifier {
        Vec<Chunk<DeclarationSpecifier>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | type_qualifier specifier_qualifier_list {
        $2.push_back(std::move($1));
        $$ = std::move($2);
    }
;

class_declarator_list:
    member_declarator {
        Vec<Chunk<ClassDeclarator>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | class_declarator_list COMMA member_declarator {
        $1.push_back(std::move($3));
        $$ = std::move($1);
    }
    | class_declarator_list COMMA {
        $$ = std::move($1);
    }
;

member_declarator:
    declarator {
        $$ = make_chunk<ClassDeclarator>(@1, std::move($1), std::nullopt);
    }
    | declarator COLON constant_expression {
        $$ = make_chunk<ClassDeclarator>(@$, std::move($1), std::move($3));
    }
    | COLON constant_expression {
        $$ = make_chunk<ClassDeclarator>(@$, std::nullopt, std::move($2));
    }
;

// Declarators
declarator:
    pointer direct_declarator {
        $$ = make_chunk<Declarator>(@$, std::move($1), std::move($2));
    }
    | direct_declarator {
        $$ = make_chunk<Declarator>(@$, std::nullopt, std::move($1));
    }
;

pointer:
    MUL {
        $$ = make_chunk<Pointer>(@1, Vec<Chunk<TypeQualifier>>{}, std::nullopt);
    }
    | MUL type_qualifier_list {
        $$ = make_chunk<Pointer>(@$, std::move($2), std::nullopt);
    }
    | MUL pointer {
        $$ = make_chunk<Pointer>(@$, Vec<Chunk<TypeQualifier>>{}, std::move($2));
    }
    | MUL type_qualifier_list pointer {
        $$ = make_chunk<Pointer>(@$, std::move($2), std::move($3));
    }
;

type_qualifier_list:
    type_qualifier {
        Vec<Chunk<TypeQualifier>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | type_qualifier_list type_qualifier {
        $1.push_back(std::move($2));
        $$ = std::move($1);
    }
;

direct_declarator:
    IDENTIFIER {
        $$ = make_chunk<IdentifierDeclarator>(@1, std::move($1));
    }
    | LPAREN declarator RPAREN {
        $$ = make_chunk<ParenDeclarator>(@$, std::move($2));
    }
    | direct_declarator LBRACKET RBRACKET {
        $$ = make_chunk<ArrayDeclarator>(@$, std::move($1), std::nullopt);
    }
    | direct_declarator LBRACKET constant_expression RBRACKET {
        $$ = make_chunk<ArrayDeclarator>(@$, std::move($1), std::move($3));
    }
    | direct_declarator LPAREN RPAREN {
        $$ = make_chunk<FunctionDeclarator>(@$, std::move($1), Vec<Chunk<ParameterDeclaration>>{}, false);
    }
    | direct_declarator LPAREN parameter_type_list RPAREN {
        $$ = make_chunk<FunctionDeclarator>(@$, std::move($1), std::move($3.first), $3.second);
  }

;

// Expressions
constant_expression:
    conditional_expression {
        $$ = make_chunk<ConstExpression>(std::move($1));
    }
;

conditional_expression:
    logical_or_expression {
        $$ = std::move($1);
    }
    | logical_or_expression QUESTION expression COLON conditional_expression %prec QUESTION {
        $$ = make_chunk<ConditionalExpression>(@$, std::move($1), std::move($3), std::move($5));
    }
;

logical_or_expression:
    logical_and_expression {
        $$ = std::move($1);
    }
    | logical_or_expression OROR logical_and_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::OROR);
    }
;

logical_and_expression:
    inclusive_or_expression {
        $$ = std::move($1);
    }
    | logical_and_expression ANDAND inclusive_or_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::ANDAND);
    }
;

inclusive_or_expression:
    exclusive_or_expression {
        $$ = std::move($1);
    }
    | inclusive_or_expression OR exclusive_or_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::OR);
    }
;

exclusive_or_expression:
    and_expression {
        $$ = std::move($1);
    }
    | exclusive_or_expression XOR and_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::XOR);
    }
;

and_expression:
    equality_expression {
        $$ = std::move($1);
    }
    | and_expression AND equality_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::AND);
    }
;

equality_expression:
    relational_expression {
        $$ = std::move($1);
    }
    | equality_expression EQ relational_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::EQ);
    }
    | equality_expression NE relational_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::NE);
    }
;

relational_expression:
    shift_expression {
        $$ = std::move($1);
    }
    | relational_expression LT shift_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::LT);
    }
    | relational_expression GT shift_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::GT);
    }
    | relational_expression LE shift_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::LE);
    }
    | relational_expression GE shift_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::GE);
    }
;

shift_expression:
    additive_expression {
        $$ = std::move($1);
    }
    | shift_expression LSHIFT additive_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::LSHIFT);
    }
    | shift_expression RSHIFT additive_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::RSHIFT);
    }
;

additive_expression:
    multiplicative_expression {
        $$ = std::move($1);
    }
    | additive_expression PLUS multiplicative_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::PLUS);
    }
    | additive_expression MINUS multiplicative_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::MINUS);
    }
;

multiplicative_expression:
    cast_expression {
        $$ = std::move($1);
    }
    | multiplicative_expression MUL cast_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::MUL);
    }
    | multiplicative_expression DIV cast_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::DIV);
    }
    | multiplicative_expression MOD cast_expression {
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::MOD);
    }
;

cast_expression:
    unary_expression {
        $$ = std::move($1);
    }
    | LPAREN type_name RPAREN cast_expression { // casting in enlightenedc is prefix because postfix is too hard.
        $$ = make_chunk<CastExpression>(@$, std::move($4), std::move($2));
    }
;

unary_expression:
    postfix_expression {
        $$ = std::move($1);
    }
    | INC unary_expression {
        $$ = make_chunk<UnaryExpression>(@$, std::move($2), ecc::tokens::UnaryOp::INC);
    }
    | DEC unary_expression {
        $$ = make_chunk<UnaryExpression>(@$, std::move($2), ecc::tokens::UnaryOp::DEC);
    }
    | unary_operator unary_expression {
        $$ = make_chunk<UnaryExpression>(@$, std::move($2), $1);
    }
    | SIZEOF unary_expression {
        $$ = make_chunk<SizeofExpression>(@$, std::move($2));
    }
    | SIZEOF LPAREN type_name RPAREN {
        $$ = make_chunk<SizeofExpression>(@$, std::move($3));
    }
;

postfix_expression:
    primary_expression {
        $$ = std::move($1);
    }
    | postfix_expression LBRACKET expression RBRACKET {
        $$ = make_chunk<ArraySubscriptExpression>(@$, std::move($1), std::move($3));
    }
    | postfix_expression LPAREN RPAREN {
        $$ = make_chunk<CallExpression>(@$, std::move($1), Vec<Chunk<Expression>>{});
    }
    | postfix_expression LPAREN argument_expression_list RPAREN {
        $$ = make_chunk<CallExpression>(@$, std::move($1), std::move($3));
    }
    | postfix_expression DOT IDENTIFIER {
        $$ = make_chunk<MemberAccessExpression>(@$, std::move($1), std::move($3), false);
    }
    | postfix_expression ARROW IDENTIFIER {
        $$ = make_chunk<MemberAccessExpression>(@$, std::move($1), std::move($3), true);
    }
    | postfix_expression DOT primitive_type {
        $$ = make_chunk<ReinterpretExpression>(@$, std::move($1), $3->pkind, false);
    }
    | postfix_expression ARROW primitive_type {
        $$ = make_chunk<ReinterpretExpression>(@$, std::move($1), $3->pkind, true);
    }
    | postfix_expression INC {
        $$ = make_chunk<PostfixExpression>(@$, std::move($1), ecc::tokens::PostfixOp::POSTINC);
    }
    | postfix_expression DEC {
        $$ = make_chunk<PostfixExpression>(@$, std::move($1), ecc::tokens::PostfixOp::POSTDEC);
    }
;

primary_expression:
    IDENTIFIER {
        $$ = make_chunk<IdentifierExpression>(@1, std::move($1));
    }
    | constant {
        $$ = std::move($1);
    }
    | string_literal {
        $$ = make_chunk<StringExpression>(@$, $1);
    }
    | LPAREN expression RPAREN {
        $2->loc = @$;
        $$ = std::move($2);
    }
;

constant:
    INT_CONST {
        $$ = make_chunk<LiteralExpression>(@1, LiteralExpression::INT, LiteralExpression::Value($1));
    }
    | CHAR_CONST {
        $$ = make_chunk<LiteralExpression>(@1, LiteralExpression::CHAR, LiteralExpression::Value($1));
    }
    | FLOAT_CONST {
        $$ = make_chunk<LiteralExpression>(@1, LiteralExpression::FLOAT, LiteralExpression::Value($1));
    }
    | TRUE {
        $$ = make_chunk<LiteralExpression>(@1, LiteralExpression::BOOL, LiteralExpression::Value(true));
    }
    | FALSE {
        $$ = make_chunk<LiteralExpression>(@1, LiteralExpression::BOOL, LiteralExpression::Value(false));
    }
;

string_literal:
    STRING_LITERAL {
        $$ = std::move($1);
    }
    | string_literal STRING_LITERAL {
        $$ = std::move($1) + std::move($2);
    }
;

expression:
    assignment_expression {
        $$ = std::move($1);
    }
    | expression COMMA assignment_expression { // See examples.ec line 198 for an example.
        $$ = make_chunk<BinaryExpression>(@$, std::move($1), std::move($3), ecc::tokens::BinaryOp::BINCOMMA);
    }
;

assignment_expression:
    conditional_expression {
        $$ = std::move($1);
    }
    | unary_expression assignment_operator assignment_expression {
        $$ = make_chunk<AssignmentExpression>(@$, std::move($1), std::move($3), $2);
    }
;

assignment_operator:
    ASSIGN { $$ = ecc::tokens::AssignOp::ASSIGN; }
    | MULEQ { $$ = ecc::tokens::AssignOp::MULEQ; }
    | DIVEQ { $$ = ecc::tokens::AssignOp::DIVEQ; }
    | MODEQ { $$ = ecc::tokens::AssignOp::MODEQ; }
    | PLUSEQ { $$ = ecc::tokens::AssignOp::PLUSEQ; }
    | MINUSEQ { $$ = ecc::tokens::AssignOp::MINUSEQ; }
    | LSHIFTEQ { $$ = ecc::tokens::AssignOp::LSHIFTEQ; }
    | RSHIFTEQ { $$ = ecc::tokens::AssignOp::RSHIFTEQ; }
    | ANDEQ { $$ = ecc::tokens::AssignOp::ANDEQ; }
    | XOREQ { $$ = ecc::tokens::AssignOp::XOREQ; }
    | OREQ { $$ = ecc::tokens::AssignOp::OREQ; }
;

unary_operator:
    AND { $$ = ecc::tokens::UnaryOp::REF; }
    | MUL { $$ = ecc::tokens::UnaryOp::DEREF; }
    | PLUS { $$ = ecc::tokens::UnaryOp::POS; }
    | MINUS { $$ = ecc::tokens::UnaryOp::NEG; }
    | TILDE { $$ = ecc::tokens::UnaryOp::TILDE; }
    | NOT { $$ = ecc::tokens::UnaryOp::NOT; }
;

argument_expression_list:
    assignment_expression {
        Vec<Chunk<Expression>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | argument_expression_list COMMA assignment_expression {
        $1.push_back(std::move($3));
        $$ = std::move($1);
    }
;

type_name:
    specifier_qualifier_list {
        $$ = make_chunk<TypeName>(@1, std::move($1), std::nullopt);
    }
    | specifier_qualifier_list abstract_declarator {
        $$ = make_chunk<TypeName>(@$, std::move($1), std::move($2));
    }
;

// Parameter types
parameter_type_list:
    parameter_list {
        $$ = { std::move($1), false };
    }
    | parameter_list COMMA ELLIPSIS { // variadic function.
        // todo: add location tracking to account for the comma and ellipsis
        $$ = { std::move($1), true };
    }
;

parameter_list:
    parameter_declaration {
        Vec<Chunk<ParameterDeclaration>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | parameter_list COMMA parameter_declaration {
        $1.push_back(std::move($3));
        $$ = std::move($1);
    }
;

parameter_declaration:
    declaration_specifier_list {
        $$ = make_chunk<ParameterDeclaration>(@1, std::move($1), std::nullopt, std::nullopt);
    }
    | declaration_specifier_list declarator {
        $$ = make_chunk<ParameterDeclaration>(@$, std::move($1), std::move($2), std::nullopt);
    }
    | declaration_specifier_list declarator ASSIGN constant_expression {
        $$ = make_chunk<ParameterDeclaration>(@$, std::move($1), std::move($2), std::move($4));
    }
    | declaration_specifier_list abstract_declarator {
        $$ = make_chunk<ParameterDeclaration>(@$, std::move($1), std::move($2), std::nullopt);
    }
;

abstract_declarator:
    pointer {
        $$ = make_chunk<Declarator>(@1, std::move($1), std::nullopt);
    }
    | pointer direct_abstract_declarator {
        $$ = make_chunk<Declarator>(@$, std::move($1), std::move($2));
    }
    | direct_abstract_declarator {
        $$ = make_chunk<Declarator>(@$, std::nullopt, std::move($1));
    }
;

direct_abstract_declarator:
    LPAREN abstract_declarator RPAREN {
        $$ = make_chunk<ParenDeclarator>(@$, std::move($2));
    }
    | direct_abstract_declarator LBRACKET RBRACKET {
        $$ = make_chunk<ArrayDeclarator>(@$, std::move($1), std::nullopt);
    }
    | direct_abstract_declarator LBRACKET constant_expression RBRACKET {
        $$ = make_chunk<ArrayDeclarator>(@$, std::move($1), std::move($3));
    }
    | direct_abstract_declarator LPAREN RPAREN {
        $$ = make_chunk<FunctionDeclarator>(@$, std::move($1), Vec<Chunk<ParameterDeclaration>>{}, false);
    }
    | direct_abstract_declarator LPAREN parameter_type_list RPAREN {
        $$ = make_chunk<FunctionDeclarator>(@$, std::move($1), std::move($3.first), $3.second);
    }
    | LBRACKET RBRACKET {
        $$ = make_chunk<ArrayDeclarator>(@$, nullptr, std::nullopt);
    }
    | LBRACKET constant_expression RBRACKET {
        $$ = make_chunk<ArrayDeclarator>(@$, nullptr, std::move($2));
    }
    | LPAREN RPAREN {
        $$ = make_chunk<FunctionDeclarator>(@$, nullptr, Vec<Chunk<ParameterDeclaration>>{}, false);
    }
    | LPAREN parameter_type_list RPAREN {
        $$ = make_chunk<FunctionDeclarator>(@$, nullptr, std::move($2.first), $2.second);
    }
;

enum_specifier:
    ENUM LBRACE enumerator_list RBRACE {
        $$ = make_chunk<EnumSpecifier>(@$, std::nullopt, std::move($3));
    }
    | primitive_type ENUM LBRACE enumerator_list RBRACE {
        $$ = make_chunk<EnumSpecifier>(@$, std::nullopt, std::move($4), $1->pkind);
    }
    | ENUM IDENTIFIER LBRACE enumerator_list RBRACE {
        type_idents.insert($2);
        $$ = make_chunk<EnumSpecifier>(@$, $2, std::move($4));
    }
    | primitive_type ENUM IDENTIFIER LBRACE enumerator_list RBRACE {
        type_idents.insert($3);
        $$ = make_chunk<EnumSpecifier>(@$, $3, std::move($5), $1->pkind);
    }
    | ENUM TYPE_IDENTIFIER LBRACE enumerator_list RBRACE {
        $$ = make_chunk<EnumSpecifier>(@$, $2, std::move($4));
    }
    | primitive_type ENUM TYPE_IDENTIFIER LBRACE enumerator_list RBRACE {
        $$ = make_chunk<EnumSpecifier>(@$, $3, std::move($5), $1->pkind);
    }
    | ENUM IDENTIFIER {
        type_idents.insert($2);
        $$ = make_chunk<EnumSpecifier>(@$, $2, std::nullopt);
    }
    | primitive_type ENUM IDENTIFIER {
        error(@$, "incomplete enum definition");
        return 1;
    }
    | ENUM TYPE_IDENTIFIER {
        $$ = make_chunk<EnumSpecifier>(@$, $2, std::nullopt);
    }
    | primitive_type ENUM TYPE_IDENTIFIER {
        error(@$, "incomplete enum definition");
        return 1;
    }
;

enumerator_list:
    enumerator {
        Vec<Chunk<Enumerator>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | enumerator_list COMMA enumerator {
        $1.push_back(std::move($3));
        $$ = std::move($1);
    }
    | enumerator_list COMMA {
        $$ = std::move($1);
    }
;

enumerator:
    IDENTIFIER {
        $$ = make_chunk<Enumerator>(@1, $1, std::nullopt);
    }
    | IDENTIFIER ASSIGN constant_expression {
        $$ = make_chunk<Enumerator>(@$, $1, std::move($3));
    }
;

type_identifier:
    TYPE_IDENTIFIER { $$ = make_chunk<TypeIdentifier>(@1, $1); }
;


// Declarations
declaration:
    declaration_specifier_list SEMI {
        $$ = make_chunk<TypeDeclaration>(@$, std::move($1));
    }
    | declaration_specifier_list init_declarator_list SEMI {
        $$ = make_chunk<VariableDeclaration>(@$, std::move($1), std::move($2));
    }
;

// Init declarators
init_declarator_list:
    init_declarator {
        Vec<Chunk<InitDeclarator>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | init_declarator_list COMMA init_declarator {
        $1.push_back(std::move($3));
        $$ = std::move($1);
    }
;

init_declarator:
    declarator {
        $$ = make_chunk<InitDeclarator>(@1, std::move($1), std::nullopt);
    }
    | declarator ASSIGN initializer {
        $$ = make_chunk<InitDeclarator>(@$, std::move($1), std::move($3));
    }
;

initializer:
    assignment_expression {
        $$ = make_chunk<Initializer>(@1, std::move($1));
    }
    | LBRACE initializer_list RBRACE { $$ = make_chunk<Initializer>(@$, std::move($2)); }
    | LBRACE initializer_list COMMA RBRACE { $$ = make_chunk<Initializer>(@$, std::move($2)); }
;

designated_initializer:
    DOT IDENTIFIER ASSIGN initializer {
        $$ = make_chunk<Initializer>(@$, $2, std::move($4));
    }
    | LBRACKET constant_expression RBRACKET ASSIGN initializer {
        $$ = make_chunk<Initializer>(@$, std::move($2), std::move($5));
    }
;

initializer_list:
    initializer {
        Vec<Chunk<Initializer>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | designated_initializer {
        Vec<Chunk<Initializer>> list;
        list.push_back(std::move($1));
        $$ = std::move(list);
    }
    | initializer_list COMMA initializer {
        $1.push_back(std::move($3));
        $$ = std::move($1);
    }
    | initializer_list COMMA designated_initializer {
        $1.push_back(std::move($3));
        $$ = std::move($1);
    }
    | initializer_list COMMA {
        $$ = std::move($1);
    }
;

compound_statement:
    LBRACE RBRACE {
        $$ = make_chunk<CompoundStatement>(@$, Vec<Chunk<ProgramItem>>{});
    }
    | LBRACE stmt_or_decl_list RBRACE {
        $$ = make_chunk<CompoundStatement>(@$, std::move($2));
    }
;

// Statements
statement:
    labeled_statement { $$ = std::move($1); }
    | expression_statement { $$ = std::move($1); }
    | print_statement{ $$ = std::move($1); }
    | compound_statement { $$ = std::move($1); }
    | selection_statement { $$ = std::move($1); }
    | iteration_statement { $$ = std::move($1); }
    | jump_statement { $$ = std::move($1); }
;

print_statement:
    string_literal SEMI {
        $$ = make_chunk<PrintStatement>(@$, std::move($1), Vec<Chunk<Expression>>{});
    }
    | string_literal COMMA argument_expression_list SEMI {
        $$ = make_chunk<PrintStatement>(@$, std::move($1), std::move($3));
    }
;

labeled_statement:
    IDENTIFIER COLON statement {
        $$ = make_chunk<LabeledStatement>(@$, std::move($1), std::move($3));
    }
    | CASE constant_expression COLON statement {
        $$ = make_chunk<CaseStatement>(@$, std::move($2), std::move($4));
    }
    | CASE constant_expression ELLIPSIS constant_expression COLON statement {
        $$ = make_chunk<CaseRangeStatement>(@$, std::move($2), std::move($4), std::move($6));
    }
    | DEFAULT COLON statement {
        $$ = make_chunk<DefaultStatement>(@$, std::move($3));
    }
;

expression_statement:
    SEMI {
        $$ = make_chunk<ExpressionStatement>(@1, std::nullopt);
    }
    | expression SEMI { // IDENTIFIER SEMI is a special case of this rule that should resolve to a call expression.
        $$ = make_chunk<ExpressionStatement>(@$, std::move($1));
    }
;

stmt_or_decl_list: // A mixed list of declarations and statements.
    declaration {
        Vec<Chunk<ProgramItem>> list;
        Chunk<ProgramItem> item = std::move($1);
        list.push_back(std::move(item));
        $$ = std::move(list);
    }
    | statement {
        Vec<Chunk<ProgramItem>> list;
        Chunk<ProgramItem> item = std::move($1);
        list.push_back(std::move(item));
        $$ = std::move(list);
    }
    | function {
        Vec<Chunk<ProgramItem>> list;
        Chunk<ProgramItem> item = std::move($1);
        list.push_back(std::move(item));
        $$ = std::move(list);
    }
    | stmt_or_decl_list declaration {
        Chunk<ProgramItem> item = std::move($2);
        $1.push_back(std::move(item));
        $$ = std::move($1);
    }
    | stmt_or_decl_list statement {
        Chunk<ProgramItem> item = std::move($2);
        $1.push_back(std::move(item));
        $$ = std::move($1);
    }
    | stmt_or_decl_list function {
        Chunk<ProgramItem> item = std::move($2);
        $1.push_back(std::move(item));
        $$ = std::move($1);
    }
;

// Selection
selection_statement:
    IF LPAREN expression RPAREN statement {
        $$ = make_chunk<IfStatement>(@$, std::move($3), std::move($5), std::nullopt);
    }
    | IF LPAREN expression RPAREN statement ELSE statement {
        $$ = make_chunk<IfStatement>(@$, std::move($3), std::move($5), std::move($7));
    }
    | SWITCH LPAREN expression RPAREN statement {
        $$ = make_chunk<SwitchStatement>(@$, std::move($3), std::move($5));
    }
;


// Iteration
iteration_statement:
    WHILE LPAREN expression RPAREN statement {
        $$ = make_chunk<WhileStatement>(@$, std::move($3), std::move($5));
    }
    | DO statement WHILE LPAREN expression RPAREN SEMI {
        $$ = make_chunk<DoWhileStatement>(@$, std::move($2), std::move($5));
    }
    | FOR LPAREN for_init_opt SEMI expression_opt SEMI expression_opt RPAREN statement {
        $$ = make_chunk<ForStatement>(@$, std::move($3), std::move($5), std::move($7), std::move($9));
    }
;

// Rules for the initialization part of the for loop, to allow for variable declarations.
for_init_opt:
    declaration_specifier_list init_declarator_list {
        $$ = make_chunk<VariableDeclaration>(@$, std::move($1), std::move($2));
    }
    | expression {
        $$ = std::move($1);
    }
    | %empty {
        $$ = std::nullopt;
    }

expression_opt: // an optional expression specifically for `for` loops where one or more loop variables are empty.
    expression { $$ = std::move($1); }
    | %empty { $$ = std::nullopt; }
;

// Jump
jump_statement:
    GOTO IDENTIFIER SEMI {
        $$ = make_chunk<GotoStatement>(@$, $2);
    }
    | BREAK SEMI {
        $$ = make_chunk<BreakStatement>(@$);
    }
    | CONTINUE SEMI {
        $$ = make_chunk<ContinueStatement>(@$);
    }
    | RETURN SEMI {
        $$ = make_chunk<ReturnStatement>(@$, std::nullopt);
    }
    | RETURN expression SEMI {
        $$ = make_chunk<ReturnStatement>(@$, std::move($2));
    }
;

%%

// FIXME: do better than this
namespace ecc::frontend {
    void Parser::error(const Location& loc, const std::string& msg) {
        throw ecc::frontend::ParseError(msg, loc);
    }
}
